version: '3.4'

services:
  auth_configuration_database:
    image: postgres:latest
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: "auth-configuration"
      POSTGRES_PASSWORD: "auth-configuration"
      POSTGRES_DB: "configuration"

  auth_persisted_database:
    image: postgres:latest
    ports:
      - "6433:5432"
    environment:
      POSTGRES_USER: "auth-persisted"
      POSTGRES_PASSWORD: "auth-persisted"
      POSTGRES_DB: "persisted"

  auth_identity_database:
    image: postgres:latest
    ports:
      - "6434:5432"
    environment:
      POSTGRES_USER: "auth-identity"
      POSTGRES_PASSWORD: "auth-identity"
      POSTGRES_DB: "identity"

  auth_admin_log_database:
    image: postgres:latest
    ports:
      - "6435:5432"
    environment:
      POSTGRES_USER: "auth-admin-log"
      POSTGRES_PASSWORD: "auth-admin-log"
      POSTGRES_DB: "admin-log"

  service_database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "mcp-migrations"
      POSTGRES_PASSWORD: "mcp-migrations"
      POSTGRES_DB: "mcp"

  auth_admin_seed:
    build:
      context: ../../../../
      dockerfile: Operations/Docker/Dockerfiles/ASPNetCore.Dockerfile
      args:
        SERVICE_NAME: "Auth.Admin"
        SERVICE_TYPE: "Authentication"
    command: ["dotnet", "Auth.Admin.dll", "/seed"]
    links:
      - auth_configuration_database
      - auth_persisted_database
      - auth_identity_database
      - auth_admin_log_database
    environment:
      ConnectionStrings__ConfigurationDbConnection: "host=auth_configuration_database;port=5432;database=configuration;username=auth-configuration;password=auth-configuration;"
      ConnectionStrings__PersistedGrantDbConnection: "host=auth_persisted_database;port=5432;database=persisted;username=auth-persisted;password=auth-persisted;"
      ConnectionStrings__IdentityDbConnection: "host=auth_identity_database;port=5432;database=identity;username=auth-identity;password=auth-identity;"
      ConnectionStrings__AdminLogDbConnection: "host=auth_admin_log_database;port=5432;database=admin-log;username=auth-admin-log;password=auth-admin-log;"
      AdminSeedConfiguration__AdminUserName: "test_admin"
      AdminSeedConfiguration__AdminPassword: "Password12345"
      AdminSeedConfiguration__AdminEmail: "admin@test.com"

