version: '3.4'

services:
  auth_configuration_database:
    image: postgres:latest
    networks:
      - service
    expose:
      - "5432"
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: "auth-configuration"
      POSTGRES_PASSWORD: "auth-configuration"
      POSTGRES_DB: "configuration"

  auth_persisted_database:
    image: postgres:latest
    networks:
      - service
    expose:
      - "5432"
    ports:
      - "6433:5432"
    environment:
      POSTGRES_USER: "auth-persisted"
      POSTGRES_PASSWORD: "auth-persisted"
      POSTGRES_DB: "persisted"

  auth_identity_database:
    image: postgres:latest
    networks:
      - service
    expose:
      - "5432"
    ports:
      - "6434:5432"
    environment:
      POSTGRES_USER: "auth-identity"
      POSTGRES_PASSWORD: "auth-identity"
      POSTGRES_DB: "identity"

  auth_admin_log_database:
    image: postgres:latest
    networks:
      - service
    expose:
      - "5432"
    ports:
      - "6435:5432"
    environment:
      POSTGRES_USER: "auth-admin-log"
      POSTGRES_PASSWORD: "auth-admin-log"
      POSTGRES_DB: "admin-log"

  auth_sts:
    build:
      context: ../../../Development
      dockerfile: ../Operations/Docker/Dockerfile
      args:
        TARGET: "Auth.STS.Identity"
    networks:
      - service
      - frontend
    expose:
      - 5000
    links:
      - auth_configuration_database
      - auth_persisted_database
      - auth_identity_database
    environment:
      VIRTUAL_HOST: "sts.mcp.testdemo.ldtteam.com"
      VIRTUAL_PORT: 5000
      VIRTUAL_PROTO: http
      ConnectionStrings__ConfigurationDbConnection: "host=auth_configuration_database;port=5432;database=configuration;username=auth-configuration;password=auth-configuration;"
      ConnectionStrings__PersistedGrantDbConnection: "host=auth_persisted_database;port=5432;database=persisted;username=auth-persisted;password=auth-persisted;"
      ConnectionStrings__IdentityDbConnection: "host=auth_identity_database;port=5432;database=identity;username=auth-identity;password=auth-identity;"

  auth_admin_api:
    build:
      context: ../../../Development
      dockerfile: ../Operations/Docker/Dockerfile
      args:
        TARGET: "Auth.Admin.Api"
    networks:
      - service
      - frontend
    expose:
      - 80
    links:
      - auth_configuration_database
      - auth_persisted_database
      - auth_identity_database
      - auth_admin_log_database
      - auth_sts
    environment:
      VIRTUAL_HOST: "api.admin.mcp.testdemo.ldtteam.com"
      VIRTUAL_PORT: 80
      VIRTUAL_PROTO: http
      ConnectionStrings__ConfigurationDbConnection: "host=auth_configuration_database;port=5432;database=configuration;username=auth-configuration;password=auth-configuration;"
      ConnectionStrings__PersistedGrantDbConnection: "host=auth_persisted_database;port=5432;database=persisted;username=auth-persisted;password=auth-persisted;"
      ConnectionStrings__IdentityDbConnection: "host=auth_identity_database;port=5432;database=identity;username=auth-identity;password=auth-identity;"
      ConnectionStrings__AdminLogDbConnection: "host=auth_admin_log_database;port=5432;database=admin-log;username=auth-admin-log;password=auth-admin-log;"
      AdminConfiguration__IdentityServerBaseUrl: "http://sts.mcp.testdemo.ldtteam.com"

  auth_admin:
    build:
      context: ../../../Development
      dockerfile: ../Operations/Docker/Dockerfile
      args:
        TARGET: "Auth.Admin"
    networks:
      - service
      - frontend
    expose:
      - 80
    links:
      - auth_configuration_database
      - auth_persisted_database
      - auth_identity_database
      - auth_admin_log_database
      - auth_sts
    environment:
      VIRTUAL_HOST: "admin.mcp.testdemo.ldtteam.com"
      VIRTUAL_PORT: 80
      VIRTUAL_PROTO: http
      ConnectionStrings__ConfigurationDbConnection: "host=auth_configuration_database;port=5432;database=configuration;username=auth-configuration;password=auth-configuration;"
      ConnectionStrings__PersistedGrantDbConnection: "host=auth_persisted_database;port=5432;database=persisted;username=auth-persisted;password=auth-persisted;"
      ConnectionStrings__IdentityDbConnection: "host=auth_identity_database;port=5432;database=identity;username=auth-identity;password=auth-identity;"
      ConnectionStrings__AdminLogDbConnection: "host=auth_admin_log_database;port=5432;database=admin-log;username=auth-admin-log;password=auth-admin-log;"
      AdminConfiguration__IdentityServerBaseUrl: "http://sts.mcp.testdemo.ldtteam.com"
      AdminConfiguration__IdentityAdminRedirectUri: "http://admin.mcp.testdemo.ldtteam.com/signin-oidc"
      AdminConfiguration__IdentityAdminBaseUrl: "http://admin.mcp.testdemo.ldtteam.com"
      AdminConfiguration__IdentityAdminApiSwaggerUIRedirectUrl: "http://admin.mcp.testdemo.ldtteam.com/swagger/oauth2-redirect.html"

  auth_admin_seed:
    build:
      context: ../../../Development
      dockerfile: ../Operations/Docker/Dockerfile
      args:
        TARGET: "Auth.Admin"
    command: ["dotnet", "Auth.Admin.dll", "/seed"]
    networks:
      - service
    links:
      - auth_configuration_database
      - auth_persisted_database
      - auth_identity_database
      - auth_admin_log_database
    environment:
      ConnectionStrings__ConfigurationDbConnection: "host=auth_configuration_database;port=5432;database=configuration;username=auth-configuration;password=auth-configuration;"
      ConnectionStrings__PersistedGrantDbConnection: "host=auth_persisted_database;port=5432;database=persisted;username=auth-persisted;password=auth-persisted;"
      ConnectionStrings__IdentityDbConnection: "host=auth_identity_database;port=5432;database=identity;username=auth-identity;password=auth-identity;"
      ConnectionStrings__AdminLogDbConnection: "host=auth_admin_log_database;port=5432;database=admin-log;username=auth-admin-log;password=auth-admin-log;"
      AdminSeedConfiguration__AdminUserName: "test_admin"
      AdminSeedConfiguration__AdminPassword: "Password12345"
      AdminSeedConfiguration__AdminEmail: "admin@test.com"

networks:
  frontend:
    external:
      name: webproxy
  service:
