version: '3.4'

services:
  service_api:
    build:
      context: ../../../../
      dockerfile: Operations/Docker/Dockerfiles/ASPNetCore.Dockerfile
      args:
        SERVICE_NAME: "Data.WebApi"
        SERVICE_TYPE: "API"
    network_mode: "host"
    environment:
      ASPNETCORE_URLS: "http://+:4000"
