version: '3.4'

services:
  auth_configuration_database:
    image: postgres:latest
    ports:
      - "6432:5432"
    environment:
      POSTGRES_USER: "auth-configuration"
      POSTGRES_PASSWORD: "auth-configuration"
      POSTGRES_DB: "configuration"

  auth_persisted_database:
    image: postgres:latest
    ports:
      - "6433:5432"
    environment:
      POSTGRES_USER: "auth-persisted"
      POSTGRES_PASSWORD: "auth-persisted"
      POSTGRES_DB: "persisted"

  auth_identity_database:
    image: postgres:latest
    ports:
      - "6434:5432"
    environment:
      POSTGRES_USER: "auth-identity"
      POSTGRES_PASSWORD: "auth-identity"
      POSTGRES_DB: "identity"

  auth_admin_log_database:
    image: postgres:latest
    ports:
      - "6435:5432"
    environment:
      POSTGRES_USER: "auth-admin-log"
      POSTGRES_PASSWORD: "auth-admin-log"
      POSTGRES_DB: "admin-log"

  service_database:
    image: postgres:latest
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: "mcp-migrations"
      POSTGRES_PASSWORD: "mcp-migrations"
      POSTGRES_DB: "mcp"
